### ISSUE TITLE
issue-19: Create the footer

### ISSUE THREAD

**Issue by XavierBurt** [flatmatefinder/flatmatefinder#19]
I'm sorry for making the issues in a really weird order, but the footer should have the following:

A "Contact Us" link that links to the contact page.
A "Terms and Conditions" link that links to the terms and conditions page.
A "Privacy Policy" link that links to the privacy policy page.
A "Meet the Team" link that links to the Meet the team page (Issue 32).
Any other stuff that might belong in the footer.

Please do work for this task in a branch named issue-19.

**Comment by amitanshusahu** [comment]
hey @XavierBurt i would like to work on this if its open
