### ISSUE TITLE
Issue-31: set up the digital ocean hosting

### ISSUE THREAD

**Issue by XavierBurt** [flatmatefinder/flatmatefinder#31]
Do the thing with the thing and boom you're done.

Please do work for this task in a branch named issue-31.

**Comment by beydlern** [comment]
Current website hosted by digital ocean: **http://64.226.112.182/**
Associated _mup.js_ and _settings.json_ files for viewing the database and application performance monitoring have been **uploaded and pinned on the group discord**.
