### ISSUE TITLE
Issue-09: Create the "For You" page

### ISSUE THREAD

**Issue by XavierBurt** [flatmatefinder/flatmatefinder#9]
The for you page should only display the cards of other people that both match with you, and that you match with. This calculation will have to be done server side. The user will have to publish their card before being able to access the For You page, and if they try to access it before hand, it will redirect them to an error page that just says "Please publish your card before attempting to access."

Please do work for this task in a branch named issue-09.

**Comment by amitanshusahu** [comment]
hey @XavierBurt i would like to work on this if its open

**Comment by XavierBurt** [comment]
Hello @amitanshusahu , I'm sorry, we're making this website as part of a school project, so we can't really accept your help, we appreciate it though, and thank you very much for your offer.

**Comment by amitanshusahu** [comment]
@XavierBurt  ,Okay i get it 😅

**Comment by KingOfMiners** [comment]
.
